import { z } from "zod";
import { structuredZhujiModuleSchema, zhujiProposalValueSchema } from "./zhuji.js";
import { AUTHORING_KNOWLEDGE_RULES, type AuthoringKnowledgeContext } from "./authoring-context.js";
import { wardrobeProposalValueSchema, type WardrobeProposal } from "./wardrobe.js";

/**
 * Public, model-facing contracts for every migrated Agent/Skill.
 *
 * These contracts intentionally contain only authoring data.  Operation ids,
 * storage revisions, leases and transport details are generated by the
 * runtime, so a creator can submit one `kind` plus its `value` without having
 * to know the persistence protocol.
 */

export const templateIdSchema = z
  .string()
  .trim()
  .min(1)
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/u);

const text = z.string().trim().min(1);
const jsonObject = z.record(z.string(), z.unknown());

export const templateProvenanceSchema = z
  .object({
    kind: z.enum(["user", "fact", "creator", "conversion", "import", "source"]),
    ref: templateIdSchema.optional(),
    requires_single_value: z.boolean().optional(),
    note: text.optional(),
  })
  .strict()
  .superRefine((value, context) => {
    if (value.kind === "fact" && value.ref === undefined) context.addIssue({ code: "custom", path: ["ref"], message: "Fact provenance requires ref" });
  });

export const templateSectionSchema = z
  .object({
    id: templateIdSchema,
    title: text,
    content: text,
    provenance: z.array(templateProvenanceSchema).default([]),
    extensions: jsonObject.default({}),
  })
  .strict();

const authorBody = {
  title: text,
  content: text,
  sections: z.array(templateSectionSchema).default([]),
  provenance: z.array(templateProvenanceSchema).default([]),
  extensions: jsonObject.default({}),
};

export const characterRelationshipTemplateSchema = z
  .object({
    target_id: templateIdSchema,
    summary: text,
    aliases: z.array(text).default([]),
    provenance: z.array(templateProvenanceSchema).default([]),
    extensions: jsonObject.default({}),
  })
  .strict();

export const characterDocumentTemplateSchema = z
  .object({
    schema_version: z.literal(1),
    id: templateIdSchema,
    display_name: text,
    aliases: z.array(text).default([]),
    summary: text,
    relationships: z.array(characterRelationshipTemplateSchema).default([]),
    sections: z.array(templateSectionSchema).default([]),
    fact_refs: z.array(templateIdSchema).default([]),
    provenance: z.array(templateProvenanceSchema).default([]),
    extensions: jsonObject.default({}),
  })
  .strict()
  .superRefine((value, context) => {
    const seen = new Set<string>();
    value.relationships.forEach((relationship, index) => {
      if (seen.has(relationship.target_id)) {
        context.addIssue({ code: "custom", path: ["relationships", index, "target_id"], message: "relationship target must be unique" });
      }
      seen.add(relationship.target_id);
    });
  });

export const characterProposalValueSchema = z
  .object({ kind: z.literal("character"), document: characterDocumentTemplateSchema })
  .strict();

export const paletteModuleKindSchema = z.enum([
  "basic_information",
  "personality_palette",
  "tri_faceted",
  "secondary_interpretation",
]);

/** A palette module keeps a stable four-module shape while allowing prose in sections. */
export const paletteModuleSchema = z
  .object({
    schema_version: z.literal(1),
    mode: z.literal("palette"),
    module: paletteModuleKindSchema,
    title: text,
    content: text,
    sections: z.record(z.string(), z.unknown()).default({}),
    provenance: z.array(templateProvenanceSchema).default([]),
    extensions: jsonObject.default({}),
  })
  .strict();

export const paletteProposalValueSchema = z
  .object({ kind: z.literal("palette"), character_id: templateIdSchema, module: paletteModuleSchema })
  .strict();

export const requiredPaletteModules = paletteModuleKindSchema.options;

export const greetingKindSchema = z.enum(["primary", "alternate", "group_only"]);

export const greetingSchema = z
  .object({
    id: templateIdSchema,
    kind: greetingKindSchema,
    content: text,
    character_ids: z.array(templateIdSchema).min(1),
    scene: text.optional(),
    perspective: text.optional(),
    player_freedom: text.optional(),
    provenance: z.array(templateProvenanceSchema).default([]),
    extensions: jsonObject.default({}),
  })
  .strict();

export const greetingsDocumentSchema = z
  .object({
    schema_version: z.literal(1),
    greetings: z.array(greetingSchema).min(1),
    extensions: jsonObject.default({}),
  })
  .strict()
  .superRefine((document, context) => {
    const ids = new Set<string>();
    let primary = 0;
    document.greetings.forEach((greeting, index) => {
      if (greeting.kind === "primary") primary += 1;
      if (ids.has(greeting.id)) context.addIssue({ code: "custom", path: ["greetings", index, "id"], message: "greeting id must be unique" });
      ids.add(greeting.id);
    });
    if (primary !== 1) context.addIssue({ code: "custom", path: ["greetings"], message: "exactly one primary greeting is required" });
  });

export const greetingsProposalValueSchema = z
  .object({ kind: z.literal("greetings"), document: greetingsDocumentSchema })
  .strict();

export const relationshipTeamCodeSchema = z.string().regex(/^[A-Z0-9]{6}$/u);

export const relationshipCharacterSummarySchema = z
  .object({ character_id: templateIdSchema, summary: text })
  .strict();

export const directionalPerspectiveSchema = z
  .object({ source_character_id: templateIdSchema, target_character_id: templateIdSchema, summary: text })
  .strict();

export const relationshipGroupSchema = z
  .object({
    id: templateIdSchema,
    name: text,
    member_ids: z.array(templateIdSchema).min(2),
    formation_cause: text,
    operating_pattern: text,
    exclusivity: text,
    latent_conflicts: z.array(text).default([]),
    joining_conditions: text,
    extensions: jsonObject.default({}),
  })
  .strict();

export const relationshipConflictTriggerSchema = z
  .object({ trigger: text, severity: z.enum(["low", "medium", "high", "critical"]) })
  .strict();

export const relationshipNetworkSummarySchema = z
  .object({
    network_character: text,
    inter_group_relations: text,
    stability: text,
    conflict_triggers: z.array(relationshipConflictTriggerSchema).default([]),
    intimacy_opportunities: z.array(text).default([]),
  })
  .strict();

export const relationshipsDocumentSchema = z
  .object({
    schema_version: z.literal(1),
    team_code: relationshipTeamCodeSchema,
    character_ids: z.array(templateIdSchema).min(2),
    character_summaries: z.array(relationshipCharacterSummarySchema),
    perspectives: z.array(directionalPerspectiveSchema),
    groups: z.array(relationshipGroupSchema).default([]),
    summary: relationshipNetworkSummarySchema,
    provenance: z.array(templateProvenanceSchema).default([]),
    extensions: jsonObject.default({}),
  })
  .strict()
  .superRefine((document, context) => {
    const participants = new Set(document.character_ids);
    if (participants.size !== document.character_ids.length) {
      context.addIssue({ code: "custom", path: ["character_ids"], message: "character ids must be unique" });
    }
    const summaries = new Set<string>();
    document.character_summaries.forEach((summary, index) => {
      if (!participants.has(summary.character_id)) context.addIssue({ code: "custom", path: ["character_summaries", index, "character_id"], message: "summary must target a participant" });
      if (summaries.has(summary.character_id)) context.addIssue({ code: "custom", path: ["character_summaries", index, "character_id"], message: "character summary must be unique" });
      summaries.add(summary.character_id);
    });
    for (const id of participants) if (!summaries.has(id)) context.addIssue({ code: "custom", path: ["character_summaries"], message: `missing summary for ${id}` });
    const pairs = new Set<string>();
    document.perspectives.forEach((perspective, index) => {
      if (!participants.has(perspective.source_character_id) || !participants.has(perspective.target_character_id)) context.addIssue({ code: "custom", path: ["perspectives", index], message: "perspective must use participant ids" });
      const key = `${perspective.source_character_id}\u0000${perspective.target_character_id}`;
      if (pairs.has(key)) context.addIssue({ code: "custom", path: ["perspectives", index], message: "perspective pair must be unique" });
      pairs.add(key);
    });
    for (const source of participants) for (const target of participants) if (!pairs.has(`${source}\u0000${target}`)) context.addIssue({ code: "custom", path: ["perspectives"], message: `missing perspective ${source} -> ${target}` });
    const groups = new Set<string>();
    document.groups.forEach((group, groupIndex) => {
      if (groups.has(group.id)) context.addIssue({ code: "custom", path: ["groups", groupIndex, "id"], message: "group id must be unique" });
      groups.add(group.id);
      const members = new Set<string>();
      group.member_ids.forEach((member, memberIndex) => {
        if (!participants.has(member)) context.addIssue({ code: "custom", path: ["groups", groupIndex, "member_ids", memberIndex], message: "group member must be a participant" });
        if (members.has(member)) context.addIssue({ code: "custom", path: ["groups", groupIndex, "member_ids", memberIndex], message: "group members must be unique" });
        members.add(member);
      });
    });
  });

export const relationshipsProposalValueSchema = z
  .object({ kind: z.literal("relationships"), document: relationshipsDocumentSchema })
  .strict();

export const worldCategorySchema = z.enum(["people", "geography", "organizations", "history", "concepts", "systems", "items", "events"]);

export const worldEntrySchema = z
  .object({
    schema_version: z.literal(1),
    id: templateIdSchema,
    category: worldCategorySchema,
    title: text,
    content: text,
    aliases: z.array(text).default([]),
    related_ids: z.array(templateIdSchema).default([]),
    keys: z.array(text).default([]),
    fact_refs: z.array(templateIdSchema).default([]),
    provenance: z.array(templateProvenanceSchema).default([]),
    extensions: jsonObject.default({}),
  })
  .strict();

export const worldProposalValueSchema = z
  .object({ kind: z.literal("world"), entries: z.array(worldEntrySchema).min(1) })
  .strict();

export const authoringModeSchema = z.enum(["zhuji", "palette"]);
export const conversionMappingSchema = z
  .object({ source: text, target: text, summary: text, provenance: text.optional(), expected_loss: text.optional() })
  .strict();

export const conversionProposalValueSchema = z
  .object({
    kind: z.literal("conversion"),
    character_id: templateIdSchema,
    source_mode: authoringModeSchema,
    target_mode: authoringModeSchema,
    modules: z.array(z.union([structuredZhujiModuleSchema, paletteModuleSchema])).min(1),
    mappings: z.array(conversionMappingSchema).min(1),
    unmapped: z.array(text).default([]),
  })
  .strict()
  .superRefine((value, context) => {
    if (value.source_mode === value.target_mode) context.addIssue({ code: "custom", path: ["target_mode"], message: "source and target modes must differ" });
    if (value.modules.some((module) => module.mode !== value.target_mode)) context.addIssue({ code: "custom", path: ["modules"], message: "all modules must use target mode" });
  });

export const importFieldMappingSchema = z
  .object({ source_field: text, target_contract: text, target_field: text, summary: text })
  .strict();

export const importAnalysisProposalValueSchema = z
  .object({
    kind: z.literal("import_analysis"),
    mappings: z.array(importFieldMappingSchema),
    losses: z.array(text).default([]),
    recommendations: z.array(text).default([]),
    source_format: z.enum(["v1", "v2", "v3", "unknown"]).default("unknown"),
  })
  .strict();

export const reviewSeveritySchema = z.enum(["error", "warning", "info"]);
export const reviewEvidenceSchema = z
  .object({ source: text, excerpt: text.optional(), path: z.array(z.union([z.string(), z.number().int()])).optional() })
  .strict();
export const reviewFindingSchema = z
  .object({ id: templateIdSchema, severity: reviewSeveritySchema, summary: text, evidence: z.array(reviewEvidenceSchema).min(1), hint: text.optional(), overridable: z.boolean().default(false) })
  .strict();

/** Internal/legacy-compatible report shape retained for critic adapters. */
export const reviewReportSchema = z
  .object({
    schema_version: z.literal(1),
    id: templateIdSchema,
    reviewer: templateIdSchema,
    target_id: templateIdSchema,
    target_revision: text,
    findings: z.array(reviewFindingSchema),
    summary: text,
    extensions: jsonObject.default({}),
  })
  .strict()
  .superRefine((report, context) => {
    const ids = new Set<string>();
    report.findings.forEach((finding, index) => {
      if (ids.has(finding.id)) context.addIssue({ code: "custom", path: ["findings", index, "id"], message: "finding id must be unique" });
      ids.add(finding.id);
    });
  });

export const reviewProposalValueSchema = z
  .object({
    kind: z.literal("review"),
    target: z.object({ kind: text, name: text, id: templateIdSchema.optional() }).strict(),
    findings: z.array(reviewFindingSchema),
    summary: text,
  })
  .strict();

export const sourceCandidateDraftSchema = z
  .object({ title: text, url: z.string().url().optional(), snippet: text.optional(), content: text.optional(), domain: text.optional(), official: z.boolean().optional() })
  .strict();

export const sourceResearchProposalValueSchema = z
  .object({
    kind: z.literal("source_research"),
    query: text,
    work_title: text.optional(),
    character_names: z.array(text).default([]),
    aliases: z.array(text).default([]),
    language: z.string().min(2).max(16).default("auto"),
    allowed_domains: z.array(text).default([]),
    candidates: z.array(sourceCandidateDraftSchema).default([]),
    notes: z.array(text).default([]),
  })
  .strict();

export const factEvidenceSchema = z
  .object({ source: text, quote: text.optional(), locator: text.optional() })
  .strict();
export const factEvidenceReferenceSchema = z
  .object({
    id: templateIdSchema.optional(),
    source_id: templateIdSchema,
    source_revision_id: text,
    chunk_set_id: templateIdSchema.optional(),
    chunk_id: templateIdSchema.optional(),
    chunk_hash: text.optional(),
    quote: text,
    character_range: z.object({ start: z.number().int().nonnegative(), end: z.number().int().nonnegative() }).strict().optional(),
    line_range: z.object({ start: z.number().int().nonnegative(), end: z.number().int().nonnegative() }).strict().optional(),
    locator: text.optional(),
  })
  .strict();
export const factClaimSchema = z
  .object({
    subject: text,
    predicate: text,
    value: text,
    classification: z.enum(["identity", "trait", "event", "relationship", "world", "other"]),
    confidence: z.number().min(0).max(1),
    coverage: z.array(text).default([]),
    evidence: z.array(factEvidenceSchema).min(1),
  })
  .strict();
export const factCurationProposalValueSchema = z
  .object({ kind: z.literal("fact_curation"), topic: text.optional(), claims: z.array(factClaimSchema).min(1), summary: text.optional() })
  .strict();

export const factDecisionSchema = z
  .object({
    fact_id: templateIdSchema.optional(),
    candidate_occurrence_id: templateIdSchema.optional(),
    claim: text,
    decision: z.enum(["accept", "reject", "conflict", "needs_evidence"]),
    reason: text,
    evidence: z.array(factEvidenceSchema).default([]),
  })
  .strict();
export const factReviewProposalValueSchema = z
  .object({ kind: z.literal("fact_review"), decisions: z.array(factDecisionSchema).min(1), summary: text })
  .strict();

export const officialPluginIdSchema = z.enum(["official.mvu-zod", "official.ejs", "official.html"]);
export const pluginCapabilitySchema = z.enum(["mvu", "ejs", "html.status_bar", "html.message_presentation", "html.greeting_selector"]);
export const jsonPointerPathSchema = z.string().refine((value) => value.startsWith("/") && !/[<>"'\\]/u.test(value), "path must be a safe JSON pointer");

const mvuNodeBase = {
  id: templateIdSchema,
  label: text,
  description: text.optional(),
  visibility: z.enum(["visible", "hidden"]).default("visible"),
  writable: z.boolean().default(false),
  update_rules: z.array(text).default([]),
};
const mvuNodeSchema: z.ZodTypeAny = z.lazy(() => z.discriminatedUnion("kind", [
  z.object({ ...mvuNodeBase, kind: z.literal("string"), default: z.string(), min_length: z.number().int().nonnegative().optional(), max_length: z.number().int().nonnegative().optional() }).strict(),
  z.object({ ...mvuNodeBase, kind: z.literal("number"), default: z.number().finite(), min: z.number().finite().optional(), max: z.number().finite().optional() }).strict(),
  z.object({ ...mvuNodeBase, kind: z.literal("integer"), default: z.number().int(), min: z.number().int().optional(), max: z.number().int().optional() }).strict(),
  z.object({ ...mvuNodeBase, kind: z.literal("boolean"), default: z.boolean() }).strict(),
  z.object({ ...mvuNodeBase, kind: z.literal("enum"), values: z.array(text).min(1), default: text }).strict().superRefine((node, context) => { if (!node.values.includes(node.default)) context.addIssue({ code: "custom", path: ["default"], message: "enum default must be one of values" }); }),
  z.object({ ...mvuNodeBase, kind: z.literal("object"), fields: z.array(z.lazy(() => mvuNodeSchema)).min(1), default: jsonObject }).strict(),
  z.object({ ...mvuNodeBase, kind: z.literal("array"), items: z.lazy(() => mvuNodeSchema), default: z.array(z.unknown()), min_items: z.number().int().nonnegative().optional(), max_items: z.number().int().nonnegative().optional() }).strict(),
]));

export const mvuVariableSchema = mvuNodeSchema;
export const mvuUpdateRuleSchema = z
  .object({ path: jsonPointerPathSchema, value: z.unknown().optional(), checks: z.array(text).default([]) })
  .strict();
export const mvuSourceSchema = z
  .object({ plugin_id: z.literal("official.mvu-zod"), variables: z.array(mvuNodeSchema).min(1), update_rules: z.array(mvuUpdateRuleSchema).default([]), description: text.optional() })
  .strict();

export const ejsConditionSchema = z
  .object({ path: jsonPointerPathSchema, operator: z.enum(["equals", "not_equals", "greater_than", "less_than", "truthy", "falsy"]), value: z.union([z.string(), z.number().finite(), z.boolean()]).optional() })
  .strict();
const ejsWhenSchema = z.union([ejsConditionSchema, z.object({ kind: z.literal("literal"), value: z.union([z.string(), z.number().finite(), z.boolean(), z.null()]) }).strict()]);
export const ejsEntrySchema = z.object({ id: templateIdSchema, when: ejsWhenSchema, content: text }).strict();
export const ejsSectionSchema = z.object({ id: templateIdSchema, branches: z.array(z.object({ when: ejsWhenSchema, content: text }).strict()).min(1), fallback: text.optional() }).strict();
export const ejsDynamicTextSchema = z.object({ id: templateIdSchema, branches: z.array(z.object({ when: ejsWhenSchema, text: text }).strict()).min(1), fallback: text.optional() }).strict();
export const ejsSourceSchema = z
  .object({ plugin_id: z.literal("official.ejs"), entries: z.array(ejsEntrySchema).default([]), sections: z.array(ejsSectionSchema).default([]), dynamic_text: z.array(ejsDynamicTextSchema).default([]), preprocessing: z.array(z.object({ id: templateIdSchema, path: jsonPointerPathSchema }).strict()).default([]) })
  .strict()
  .superRefine((source, context) => {
    if (source.entries.length === 0 && source.sections.length === 0 && source.dynamic_text.length === 0) context.addIssue({ code: "custom", path: ["entries"], message: "EJS needs entries, sections or dynamic text" });
    const textValues = [
      ...source.entries.map((entry) => [entry.content]),
      ...source.sections.flatMap((section) => [...section.branches.map((branch) => branch.content), ...(section.fallback === undefined ? [] : [section.fallback])]),
      ...source.dynamic_text.flatMap((dynamic) => [...dynamic.branches.map((branch) => branch.text), ...(dynamic.fallback === undefined ? [] : [dynamic.fallback])]),
    ].flat();
    textValues.forEach((value, index) => { if (value.includes("<%") || value.includes("%>")) context.addIssue({ code: "custom", path: ["entries", index, "content"], message: "authored EJS text cannot contain raw delimiters" }); });
  });

export const htmlFeatureSchema = z.enum(["status_bar", "message_presentation", "greeting_selector"]);
export const htmlComponentSchema = z
  .object({
    id: templateIdSchema,
    feature: htmlFeatureSchema,
    tag: z.enum(["div", "span", "p", "section", "header", "footer", "ul", "ol", "li", "button", "label", "input", "select", "option", "progress", "strong", "em", "small"]),
    label: text,
    text: z.array(z.object({ kind: z.literal("text"), value: z.string() }).strict()).default([]),
    binding_paths: z.array(jsonPointerPathSchema).default([]),
  })
  .strict();
export const htmlSourceSchema = z
  .object({ plugin_id: z.literal("official.html"), features: z.array(htmlFeatureSchema).min(1), components: z.array(htmlComponentSchema).min(1) })
  .strict()
  .superRefine((source, context) => {
    const features = new Set(source.features);
    const ids = new Set<string>();
    source.components.forEach((component, index) => {
      if (!features.has(component.feature)) context.addIssue({ code: "custom", path: ["components", index, "feature"], message: "component feature must be enabled" });
      if (ids.has(component.id)) context.addIssue({ code: "custom", path: ["components", index, "id"], message: "component id must be unique" });
      ids.add(component.id);
      if ((component.tag === "input") && component.text.length > 0) context.addIssue({ code: "custom", path: ["components", index, "text"], message: "input cannot contain text children" });
    });
  });

export const pluginSourceSchema = z.discriminatedUnion("plugin_id", [mvuSourceSchema, ejsSourceSchema, htmlSourceSchema]);
export const pluginProposalValueSchema = z
  .object({
    kind: z.literal("plugin"),
    plugin_id: officialPluginIdSchema,
    capabilities: z.array(pluginCapabilitySchema).default([]),
    source: pluginSourceSchema,
    description: text.optional(),
  })
  .strict()
  .superRefine((value, context) => {
    if (value.source.plugin_id !== value.plugin_id) context.addIssue({ code: "custom", path: ["source", "plugin_id"], message: "source plugin id must match proposal" });
    const expected = value.plugin_id === "official.mvu-zod" ? "mvu" : value.plugin_id === "official.ejs" ? "ejs" : undefined;
    if (expected !== undefined && value.capabilities.length > 0 && !value.capabilities.includes(expected)) context.addIssue({ code: "custom", path: ["capabilities"], message: `plugin must include ${expected} capability` });
    if (value.plugin_id === "official.html" && value.capabilities.length > 0 && value.capabilities.some((capability) => !capability.startsWith("html."))) context.addIssue({ code: "custom", path: ["capabilities"], message: "HTML capabilities must be html.*" });
  });

export const directorRoutingProposalValueSchema = z
  .object({
    kind: z.literal("director_routing"),
    phase: z.enum(["intake", "research", "authoring", "review", "build", "publish", "blocked", "complete"]),
    next_action: text,
    question: text.optional(),
    must_not_emit: z.array(text).default([]),
    reason: text.optional(),
  })
  .strict();

export const templateProposalValueSchema = z.discriminatedUnion("kind", [
  characterProposalValueSchema,
  zhujiProposalValueSchema,
  paletteProposalValueSchema,
  wardrobeProposalValueSchema,
  greetingsProposalValueSchema,
  relationshipsProposalValueSchema,
  worldProposalValueSchema,
  conversionProposalValueSchema,
  importAnalysisProposalValueSchema,
  reviewProposalValueSchema,
  sourceResearchProposalValueSchema,
  factCurationProposalValueSchema,
  factReviewProposalValueSchema,
  pluginProposalValueSchema,
  directorRoutingProposalValueSchema,
]);

export const templateProposalJsonSchema = z.toJSONSchema(templateProposalValueSchema);

export type TemplateProposalValue = z.infer<typeof templateProposalValueSchema>;
export type TemplateKind = TemplateProposalValue["kind"];
export type CharacterDocumentTemplate = z.infer<typeof characterDocumentTemplateSchema>;
export type PaletteModuleKind = z.infer<typeof paletteModuleKindSchema>;
export type PaletteModule = z.infer<typeof paletteModuleSchema>;
export type GreetingsDocument = z.infer<typeof greetingsDocumentSchema>;
export type RelationshipsDocument = z.infer<typeof relationshipsDocumentSchema>;
export type WorldEntry = z.infer<typeof worldEntrySchema>;
export type ReviewFinding = z.infer<typeof reviewFindingSchema>;
export type FactClaim = z.infer<typeof factClaimSchema>;
export type FactDecision = z.infer<typeof factDecisionSchema>;
export type PluginSource = z.infer<typeof pluginSourceSchema>;
export type WardrobeProposalValue = WardrobeProposal;

export const TEMPLATE_BINDINGS: Readonly<Record<string, TemplateKind[]>> = {
  "director-orchestration": ["director_routing"],
  "source-research": ["source_research"],
  "fact-curation": ["fact_curation"],
  "fact-review": ["fact_review"],
  "zhuji-creation": ["zhuji"],
  "palette-creation": ["palette"],
  "wardrobe-creation": ["wardrobe"],
  "character-critique": ["review"],
  "relationship-creation": ["relationships"],
  "greetings-creation": ["greetings"],
  "greetings-critique": ["review"],
  "mode-conversion": ["conversion"],
  "card-import-analysis": ["import_analysis"],
  "world-lore-creation": ["world"],
  "world-lore-critique": ["review"],
  "mvu-creation": ["plugin"],
  "mvu-critique": ["review"],
  "ejs-creation": ["plugin"],
  "ejs-critique": ["review"],
  "html-creation": ["plugin"],
  "html-critique": ["review"],
};

export const TEMPLATE_GUIDES: Readonly<Record<TemplateKind, { skill: string; title: string; required: readonly string[]; example: unknown }>> = {
  character: { skill: "character-authoring", title: "Character document", required: ["document.schema_version", "document.id", "document.display_name", "document.summary"], example: { kind: "character", document: { schema_version: 1, id: "demo", display_name: "Demo", summary: "A concise character summary" } } },
  zhuji: { skill: "zhuji-creation", title: "Zhuji seven-module character mode", required: ["character_id", "module.module", "module.data"], example: { kind: "zhuji", character_id: "demo", module: "read workspace_zhuji_context for a module-specific example" } },
  palette: { skill: "palette-creation", title: "Palette module", required: ["character_id", "module.module", "module.title", "module.content"], example: { kind: "palette", character_id: "demo", module: { schema_version: 1, mode: "palette", module: "basic_information", title: "Basic information", content: "A compact palette description" } } },
  wardrobe: { skill: "wardrobe-creation", title: "Cross-mode wardrobe", required: ["character_id", "content"], example: { kind: "wardrobe", character_id: "demo", content: "wardrobe.md tables must include 款式、顏色、材質、數量、主要場合、狀態、備註; same cut in different colors must be separate rows with concrete fit, care, storage and use notes" } },
  greetings: { skill: "greetings-creation", title: "Greetings document", required: ["document.greetings", "one greeting.kind=primary"], example: { kind: "greetings", document: { schema_version: 1, greetings: [{ id: "arrival", kind: "primary", content: "Hello.", character_ids: ["demo"] }] } } },
  relationships: { skill: "relationship-creation", title: "Relationship network", required: ["document.character_ids", "document.character_summaries", "document.perspectives", "document.summary"], example: { kind: "relationships", document: "include every participant pair in perspectives" } },
  world: { skill: "world-lore-creation", title: "World lore entries", required: ["entries", "entries[].category", "entries[].title", "entries[].content"], example: { kind: "world", entries: [{ schema_version: 1, id: "harbor", category: "geography", title: "Harbor", content: "A coastal city" }] } },
  conversion: { skill: "mode-conversion", title: "Mode conversion", required: ["character_id", "source_mode", "target_mode", "modules", "mappings"], example: { kind: "conversion", character_id: "demo", source_mode: "zhuji", target_mode: "palette", modules: [], mappings: [{ source: "appearance", target: "basic_information", summary: "maps appearance to basic information" }] } },
  import_analysis: { skill: "card-import-analysis", title: "Card import mapping", required: ["mappings", "losses", "recommendations"], example: { kind: "import_analysis", mappings: [{ source_field: "/name", target_contract: "character", target_field: "/display_name", summary: "direct mapping" }] } },
  review: { skill: "*-critique", title: "Review report", required: ["target", "findings[].severity", "findings[].evidence", "summary"], example: { kind: "review", target: { kind: "greetings", name: "current" }, findings: [], summary: "No blocking findings" } },
  source_research: { skill: "source-research", title: "Source research candidates", required: ["query", "candidates"], example: { kind: "source_research", query: "official character page", candidates: [{ title: "Official page", url: "https://example.test" }] } },
  fact_curation: { skill: "fact-curation", title: "Fact candidates", required: ["claims[].subject", "claims[].predicate", "claims[].value", "claims[].evidence"], example: { kind: "fact_curation", claims: [{ subject: "demo", predicate: "has_trait", value: "calm", classification: "trait", confidence: 0.9, evidence: [{ source: "official page" }] }] } },
  fact_review: { skill: "fact-review", title: "Fact review decisions", required: ["decisions[].candidate_occurrence_id", "decisions[].claim", "decisions[].decision", "decisions[].reason", "summary"], example: { kind: "fact_review", decisions: [{ candidate_occurrence_id: "candidate-occurrence-from-context", claim: "demo is calm", decision: "accept", reason: "supported by source", evidence_refs: [{ source_id: "source-from-context", source_revision_id: "source-version-from-context", chunk_id: "chunk-from-context", chunk_hash: "hash-from-context", quote: "demo is calm" }] }], summary: "Accepted supported claims" } },
  plugin: { skill: "mvu/ejs/html-creation", title: "Typed plugin proposal", required: ["plugin_id", "source"], example: { kind: "plugin", plugin_id: "official.html", source: { plugin_id: "official.html", features: ["status_bar"], components: [{ id: "status", feature: "status_bar", tag: "div", label: "Status" }] } } },
  director_routing: { skill: "director-orchestration", title: "Director routing decision", required: ["phase", "next_action"], example: { kind: "director_routing", phase: "authoring", next_action: "ask the creator to draft the selected template" } },
};

const TEMPLATE_SCHEMAS: Readonly<Record<TemplateKind, z.ZodTypeAny>> = {
  character: characterProposalValueSchema,
  zhuji: zhujiProposalValueSchema,
  palette: paletteProposalValueSchema,
  wardrobe: wardrobeProposalValueSchema,
  greetings: greetingsProposalValueSchema,
  relationships: relationshipsProposalValueSchema,
  world: worldProposalValueSchema,
  conversion: conversionProposalValueSchema,
  import_analysis: importAnalysisProposalValueSchema,
  review: reviewProposalValueSchema,
  source_research: sourceResearchProposalValueSchema,
  fact_curation: factCurationProposalValueSchema,
  fact_review: factReviewProposalValueSchema,
  plugin: pluginProposalValueSchema,
  director_routing: directorRoutingProposalValueSchema,
};

export function templateSchemaFor(kind: TemplateKind): z.ZodTypeAny {
  return TEMPLATE_SCHEMAS[kind];
}

export function templateJsonSchemaFor(kind: TemplateKind): Record<string, unknown> {
  return z.toJSONSchema(templateSchemaFor(kind)) as Record<string, unknown>;
}

export interface TemplateInstance {
  readonly artifact_id?: string;
  readonly kind: TemplateKind;
  readonly name: string;
  readonly value: unknown;
  readonly content?: unknown;
  readonly markdown?: string;
  readonly revision?: string;
}

export function buildTemplateContext(kind: TemplateKind, existing: readonly TemplateInstance[] = [], knowledge?: AuthoringKnowledgeContext) {
  return {
    contract_version: 1,
    kind,
    guide: TEMPLATE_GUIDES[kind],
    schema: templateJsonSchemaFor(kind),
    authoring_knowledge_rules: AUTHORING_KNOWLEDGE_RULES,
    existing: existing.filter((item) => item.kind === kind),
    ...(knowledge === undefined ? {} : { knowledge }),
  };
}
