import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { TextDecoder } from "node:util";
import { HttpSourceFetcher } from "@st-workspace/adapters";
import { FileAttachmentStore, FileProjectRepository, templateProposalJsonSchema, type AdaptationDecision, type RequestResult, type SourceAttachment, zhujiProposalJsonSchema } from "@st-workspace/core";
import { AgentAdapter, AgentRouter, WorkspaceProjectManager, WorkspaceRuntime, WorkspaceWorker, type WorkspaceWorkerOptions } from "@st-workspace/runtime";

export interface WorkspaceServerOptions {
  runtime?: WorkspaceRuntime;
  projectManager?: WorkspaceProjectManager;
  actor?: string;
  worker?: WorkspaceWorker;
  workerOptions?: WorkspaceWorkerOptions;
  autoStartWorker?: boolean;
}

export interface WorkspaceServer extends Server {
  readonly workspaceWorker: WorkspaceWorker;
}

const supportedMcpProtocolVersions = new Set(["2025-11-25", "2025-06-18"]);

function mcpProtocolVersion(params: unknown): string {
  if (params !== null && typeof params === "object") {
    const requested = (params as { protocolVersion?: unknown }).protocolVersion;
    if (typeof requested === "string" && supportedMcpProtocolVersions.has(requested)) return requested;
  }
  return "2025-11-25";
}

// OpenCode's MCP schema validator requires every tool input schema to declare
// a top-level object type. The template contract is a oneOf of object shapes,
// so the generated JSON Schema omits that redundant discriminator. Adding it
// at the MCP boundary preserves the contract while keeping the schema valid
// for OpenCode and other strict MCP clients.
const templateProposalMcpInputSchema: Record<string, unknown> = { ...(templateProposalJsonSchema as Record<string, unknown>), type: "object" };

export const toolDefinitions = [
  {
    name: "workspace_request",
    description: "Execute a natural-language workspace intent.",
    inputSchema: { type: "object", additionalProperties: false, properties: { request: { type: "string" }, agent: { type: "string", description: "Optional visible Agent id or alias. Omit to let Director route the intent." } }, required: ["request"] },
  },
  {
    name: "workspace_status",
    description: "Read the current workspace operation status.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_agents",
    description: "List the visible Agents, their roles, and the default Director route.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_zhuji_context",
    description: "Read the Zhuji Creator contract, seven module guides, JSON Schema, and existing module instances.",
    inputSchema: { type: "object", additionalProperties: false, properties: { character_id: { type: "string", description: "Optional character id used to filter existing module instances." } } },
  },
  {
    name: "workspace_zhuji_submit",
    description: "Submit one validated Zhuji module proposal. The proposal must match the seven-module JSON Schema.",
    inputSchema: zhujiProposalJsonSchema,
  },
  {
    name: "workspace_template_context",
    description: "Read the fixed template contract, JSON Schema, guide and existing examples for one Agent/Skill output kind.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        kind: {
          type: "string",
          enum: ["character", "zhuji", "palette", "wardrobe", "greetings", "relationships", "world", "conversion", "import_analysis", "review", "source_research", "fact_curation", "fact_review", "plugin", "director_routing"],
        },
      },
      required: ["kind"],
    },
  },
  {
    name: "workspace_template_submit",
    description: "Submit one validated high-level template value. Internal operation and storage details are generated by the workspace.",
    inputSchema: templateProposalMcpInputSchema,
  },
  {
    name: "workspace_issue_update",
    description: "Resolve, ignore, or override one review issue. Ignore and override are allowed only for overridable findings and every action needs a reason.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        issue_id: { type: "string" },
        action: { type: "string", enum: ["resolve", "ignore", "override"] },
        reason: { type: "string" },
        severity: { type: "string", enum: ["critical", "error", "warning", "info"] },
        agent: { type: "string", description: "Optional trusted execution agent; defaults to Director." },
      },
      required: ["issue_id", "action", "reason"],
    },
  },
  {
    name: "workspace_authoring_context",
    description: "Read Blueprint, accepted and unresolved Facts, source records, and adaptation decisions for Creator authoring.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_source_candidates",
    description: "List source candidates and their explicit selection state.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_source_select",
    description: "Explicitly approve or reject source candidate ids before source ingestion.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        decisions: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: { candidate_id: { type: "string" }, decision: { type: "string", enum: ["approve", "reject"] } },
            required: ["candidate_id", "decision"],
          },
        },
      },
      required: ["decisions"],
    },
  },
  {
    name: "workspace_adaptation_decision",
    description: "Record how a deliberate Blueprint-versus-canon difference should be handled.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        topic: { type: "string" },
        choice: { type: "string", enum: ["keep_blueprint", "adopt_fact", "blend", "defer"] },
        blueprint_refs: { type: "array", items: { type: "string" } },
        fact_refs: { type: "array", items: { type: "string" } },
        rationale: { type: "string" },
      },
      required: ["topic", "choice", "rationale"],
    },
  },
  {
    name: "workspace_interview_context",
    description: "Read exactly one current high-level project interview question and its saved answers. Do not treat this as a batch questionnaire.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_interview_answer",
    description: "Answer exactly the current project interview question. The workspace stores one answer atomically and returns one next question; it does not accept batch answers.",
    inputSchema: { type: "object", additionalProperties: false, properties: { answer: { type: "string" } }, required: ["answer"] },
  },
  {
    name: "workspace_projects",
    description: "List projects available inside the workspace projects folder.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_project_select",
    description: "Select an existing project by its visible name or folder name.",
    inputSchema: { type: "object", additionalProperties: false, properties: { project: { type: "string" } }, required: ["project"] },
  },
] as const;

function json(response: ServerResponse, status: number, value: unknown): void {
  response.statusCode = status;
  response.setHeader("content-type", "application/json; charset=utf-8");
  response.end(JSON.stringify(value));
}

class RequestBodyError extends Error {
  readonly code = "REQUEST_INVALID_UTF8";
  readonly recoverable = true;

  constructor() {
    super("Request body is not valid UTF-8");
    this.name = "RequestBodyError";
  }
}

async function body(request: IncomingMessage): Promise<unknown> {
  const chunks: Buffer[] = [];
  for await (const chunk of request) chunks.push(Buffer.from(chunk));
  if (chunks.length === 0) return {};
  let text: string;
  try {
    text = new TextDecoder("utf-8", { fatal: true }).decode(Buffer.concat(chunks));
  } catch {
    throw new RequestBodyError();
  }
  return JSON.parse(text) as unknown;
}

function attachmentsFrom(value: unknown): SourceAttachment[] {
  if (!Array.isArray(value)) return [];
  return value.flatMap((item): SourceAttachment[] => {
    if (item === null || typeof item !== "object") return [];
    const candidate = item as { name?: unknown; content_base64?: unknown; media_type?: unknown };
    if (typeof candidate.name !== "string" || typeof candidate.content_base64 !== "string") return [];
    return [{ name: candidate.name, content: new Uint8Array(Buffer.from(candidate.content_base64, "base64")), ...(typeof candidate.media_type === "string" ? { media_type: candidate.media_type } : {}) }];
  });
}

function dashboard(): string {
  return `<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>ST Workspace</title><style>body{font-family:system-ui;max-width:980px;margin:40px auto;padding:0 20px;color:#202124}.layout{display:grid;grid-template-columns:280px 1fr;gap:24px}.panel{border:1px solid #ddd;border-radius:10px;padding:16px;background:#fff}body{background:#fafafa}textarea{width:100%;min-height:90px;box-sizing:border-box}button,select{margin-top:8px;padding:8px 12px}button{cursor:pointer}.agent{padding:8px 0;border-bottom:1px solid #eee}.agent:last-child{border-bottom:0}.agent small{display:block;color:#666;margin-top:3px}pre{background:#f5f5f5;padding:16px;white-space:pre-wrap;min-height:120px}.badge{display:inline-block;font-size:12px;background:#e8f0fe;color:#174ea6;border-radius:999px;padding:2px 7px;margin-left:4px}</style><h1>ST Workspace</h1><p>以自然語言操作；左側可檢視並指定 Agent，未指定時由 Director 自動路由。</p><div class="layout"><aside class="panel"><h2>Agents</h2><label for="agent">執行 Agent</label><select id="agent"><option value="">Director（自動路由）</option></select><div id="agentList">載入中…</div></aside><main class="panel"><textarea id="request" placeholder="例如：建立珠璣角色 Yukino，或預覽目前卡片"></textarea><br><button onclick="run()">執行</button> <button onclick="status()">狀態</button><pre id="out">尚未執行</pre></main></div><script>const out=document.querySelector('#out');const selector=document.querySelector('#agent');const list=document.querySelector('#agentList');async function json(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});return await r.json()}async function loadAgents(){const data=await json('/workspace/agents');for(const agent of data.agents){const option=document.createElement('option');option.value=agent.id;option.textContent=agent.id;selector.appendChild(option);const row=document.createElement('div');row.className='agent';row.innerHTML='<strong>'+agent.id+'</strong>'+(agent.id===data.default_agent?'<span class="badge">default</span>':'')+'<small>'+agent.role+' · '+agent.intents.join(', ')+'</small>';list.appendChild(row)}}async function run(){const body={request:document.querySelector('#request').value};if(selector.value)body.agent=selector.value;out.textContent=JSON.stringify(await json('/workspace/request',body),null,2)}async function status(){out.textContent=JSON.stringify(await json('/workspace/status'),null,2)}loadAgents();</script>`;
}

function requestValue(value: unknown): string | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const request = (value as { request?: unknown }).request;
  return typeof request === "string" && request.trim().length > 0 ? request : undefined;
}

function agentValue(value: unknown): string | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const agent = (value as { agent?: unknown }).agent;
  return typeof agent === "string" && agent.trim().length > 0 ? agent : undefined;
}

function characterIdValue(value: unknown): string | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const characterId = (value as { character_id?: unknown }).character_id;
  return typeof characterId === "string" && characterId.trim().length > 0 ? characterId : undefined;
}

const templateKinds = new Set(["character", "zhuji", "palette", "wardrobe", "greetings", "relationships", "world", "conversion", "import_analysis", "review", "source_research", "fact_curation", "fact_review", "plugin", "director_routing"]);

function templateKindValue(value: unknown): string | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const kind = (value as { kind?: unknown }).kind;
  return typeof kind === "string" && templateKinds.has(kind) ? kind : undefined;
}

function answerValue(value: unknown): string | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const answer = (value as { answer?: unknown }).answer;
  return typeof answer === "string" ? answer : undefined;
}

function projectValue(value: unknown): string | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const project = (value as { project?: unknown }).project;
  return typeof project === "string" && project.trim().length > 0 ? project : undefined;
}

function sourceSelectionValue(value: unknown): Array<{ candidate_id: string; decision: "approve" | "reject" }> | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const decisions = (value as { decisions?: unknown }).decisions;
  if (!Array.isArray(decisions) || decisions.length === 0) return undefined;
  const parsed = decisions.flatMap((item): Array<{ candidate_id: string; decision: "approve" | "reject" }> => {
    if (item === null || typeof item !== "object") return [];
    const candidate = item as { candidate_id?: unknown; decision?: unknown };
    if (typeof candidate.candidate_id !== "string" || (candidate.decision !== "approve" && candidate.decision !== "reject")) return [];
    return [{ candidate_id: candidate.candidate_id, decision: candidate.decision }];
  });
  return parsed.length === decisions.length ? parsed : undefined;
}

function issueUpdateValue(value: unknown): { issue_id: string; action: "resolve" | "ignore" | "override"; reason: string; severity?: "critical" | "error" | "warning" | "info"; agent?: string } | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const input = value as { issue_id?: unknown; action?: unknown; reason?: unknown; severity?: unknown; agent?: unknown };
  if (typeof input.issue_id !== "string" || typeof input.reason !== "string") return undefined;
  if (input.action !== "resolve" && input.action !== "ignore" && input.action !== "override") return undefined;
  if (input.severity !== undefined && input.severity !== "critical" && input.severity !== "error" && input.severity !== "warning" && input.severity !== "info") return undefined;
  if (input.agent !== undefined && typeof input.agent !== "string") return undefined;
  return {
    issue_id: input.issue_id,
    action: input.action,
    reason: input.reason,
    ...(input.severity === undefined ? {} : { severity: input.severity }),
    ...(input.agent === undefined ? {} : { agent: input.agent }),
  };
}

function adaptationDecisionValue(value: unknown): Omit<AdaptationDecision, "id" | "created_at" | "created_by"> | undefined {
  if (value === null || typeof value !== "object") return undefined;
  const input = value as { topic?: unknown; choice?: unknown; blueprint_refs?: unknown; fact_refs?: unknown; rationale?: unknown };
  if (typeof input.topic !== "string" || typeof input.rationale !== "string" || !["keep_blueprint", "adopt_fact", "blend", "defer"].includes(String(input.choice))) return undefined;
  const strings = (items: unknown): string[] | undefined => {
    if (items === undefined) return undefined;
    if (!Array.isArray(items) || items.some((item) => typeof item !== "string")) return undefined;
    return items as string[];
  };
  const blueprintRefs = strings(input.blueprint_refs);
  const factRefs = strings(input.fact_refs);
  if (input.blueprint_refs !== undefined && blueprintRefs === undefined) return undefined;
  if (input.fact_refs !== undefined && factRefs === undefined) return undefined;
  return {
    topic: input.topic,
    choice: input.choice as AdaptationDecision["choice"],
    ...(blueprintRefs === undefined ? {} : { blueprint_refs: blueprintRefs }),
    ...(factRefs === undefined ? {} : { fact_refs: factRefs }),
    rationale: input.rationale,
  };
}

function visibleAgents(agentAdapter: AgentAdapter): { default_agent: string; agents: ReturnType<AgentAdapter["list"]> } {
  return { default_agent: "director", agents: agentAdapter.list() };
}

export function createWorkspaceServer(options: WorkspaceServerOptions): WorkspaceServer {
  const actor = options.actor ?? "agent";
  if (options.runtime === undefined && options.projectManager === undefined) throw new Error("workspace server requires a runtime or project manager");
  const router = new AgentRouter();
  const runtimeForWorker = options.projectManager === undefined
    ? options.runtime
    : () => options.projectManager!.ensureRuntime();
  if (runtimeForWorker === undefined) throw new Error("workspace server could not initialize a runtime");
  const worker = options.worker ?? new WorkspaceWorker(runtimeForWorker, { actor: `${actor}-worker`, ...options.workerOptions });
  const getRuntime = async (): Promise<WorkspaceRuntime> => options.projectManager === undefined ? options.runtime! : options.projectManager.ensureRuntime();
  const getAgentAdapter = async (): Promise<AgentAdapter> => new AgentAdapter(await getRuntime(), router);
  if (options.autoStartWorker ?? true) worker.start();
  const server = createServer(async (request, response) => {
    try {
      const url = new URL(request.url ?? "/", "http://localhost");
      if (request.method === "GET" && url.pathname === "/") {
        response.statusCode = 200;
        response.setHeader("content-type", "text/html; charset=utf-8");
        response.end(dashboard());
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/status") {
        json(response, 200, options.projectManager === undefined ? await options.runtime!.status() : await options.projectManager.status());
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/health") {
        json(response, 200, { status: "ready", worker: worker.status() });
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/agents") {
        json(response, 200, visibleAgents(await getAgentAdapter()));
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/zhuji/context") {
        json(response, 200, await (await getRuntime()).zhujiContext(url.searchParams.get("character_id") ?? undefined));
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/template/context") {
        const kind = url.searchParams.get("kind");
        if (kind === null || !templateKinds.has(kind)) {
          json(response, 400, { error: "TEMPLATE_KIND_REQUIRED" });
          return;
        }
        json(response, 200, await (await getRuntime()).templateContext(kind as Parameters<WorkspaceRuntime["templateContext"]>[0]));
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/authoring/context") {
        json(response, 200, await (await getRuntime()).authoringKnowledgeContext());
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/source/candidates") {
        json(response, 200, { candidates: await (await getRuntime()).sourceCandidates() });
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/interview/context") {
        json(response, 200, await (await getRuntime()).interviewContext());
        return;
      }
      if (request.method === "GET" && url.pathname === "/workspace/projects") {
        if (options.projectManager === undefined) {
          json(response, 200, { projects: [] });
        } else {
          const manager = options.projectManager;
          await manager.ensureRuntime();
          const projects = await manager.listProjects();
          const current = await manager.repository.read();
          const visible = current.project_status === "uninitialized" && current.interview.status === "idle" && current.operations.length === 0
            ? projects.filter((project) => project.project_id !== current.project_id)
            : projects;
          json(response, 200, { projects: visible });
        }
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/request") {
        const parsed = await body(request);
        const requestText = requestValue(parsed);
        if (requestText === undefined) {
          json(response, 400, { error: "REQUEST_REQUIRED" });
          return;
        }
        const input = parsed as { attachments?: unknown };
        const requestedAgent = agentValue(parsed);
        const result = options.projectManager === undefined
          ? await (await getAgentAdapter()).request({ request: requestText, context: { actor, attachments: attachmentsFrom(input.attachments) }, ...(requestedAgent === undefined ? {} : { agent: requestedAgent }) })
          : await options.projectManager.request(requestText, { actor, attachments: attachmentsFrom(input.attachments) }, requestedAgent === undefined ? {} : { agent: requestedAgent });
        json(response, 200, result);
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/interview/answer") {
        const parsed = await body(request);
        const answer = answerValue(parsed);
        if (answer === undefined) {
          json(response, 400, { error: "ANSWER_REQUIRED" });
          return;
        }
        const result = options.projectManager === undefined
          ? await (await getRuntime()).answerInterview(answer, { actor, attachments: [] })
          : await options.projectManager.answerInterview(answer, { actor, attachments: [] });
        json(response, 200, result);
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/source/select") {
        const parsed = await body(request);
        const decisions = sourceSelectionValue(parsed);
        if (decisions === undefined) {
          json(response, 400, { error: "SOURCE_SELECTION_REQUIRED" });
          return;
        }
        json(response, 200, await (await getRuntime()).selectSourceCandidates(decisions, { actor, attachments: [] }));
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/adaptation/decision") {
        const parsed = await body(request);
        const decision = adaptationDecisionValue(parsed);
        if (decision === undefined) {
          json(response, 400, { error: "ADAPTATION_DECISION_REQUIRED" });
          return;
        }
        json(response, 200, await (await getRuntime()).createAdaptationDecision(decision, { actor, attachments: [] }));
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/project/select") {
        const parsed = await body(request);
        const project = projectValue(parsed);
        if (project === undefined || options.projectManager === undefined) {
          json(response, 400, { error: project === undefined ? "PROJECT_REQUIRED" : "PROJECT_MANAGER_REQUIRED" });
          return;
        }
        json(response, 200, await options.projectManager.select(project));
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/zhuji") {
        const parsed = await body(request);
        const result = await (await getRuntime()).submitZhujiProposal(parsed, { actor, attachments: [] });
        json(response, 200, result);
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/template") {
        const parsed = await body(request);
        const result = await (await getRuntime()).submitTemplateProposal(parsed, { actor, attachments: [] });
        json(response, 200, result);
        return;
      }
      if (request.method === "POST" && url.pathname === "/workspace/issue") {
        const parsed = await body(request);
        const input = issueUpdateValue(parsed);
        if (input === undefined) {
          json(response, 400, { error: "ISSUE_UPDATE_REQUIRED" });
          return;
        }
        const { agent, ...issue } = input;
        json(response, 200, await (await getRuntime()).updateIssue(issue, { actor, attachments: [] }, agent === undefined ? {} : { agent }));
        return;
      }
      if (request.method === "POST" && url.pathname === "/mcp") {
        const parsed = await body(request) as { id?: unknown; method?: unknown; params?: unknown };
        const id = parsed.id ?? null;
        if (parsed.method === "initialize") {
          json(response, 200, { jsonrpc: "2.0", id, result: { protocolVersion: mcpProtocolVersion(parsed.params), capabilities: { tools: { listChanged: false } }, serverInfo: { name: "st-workspace-v3", version: "0.1.0" } } });
          return;
        }
        if (parsed.method === "tools/list") {
          json(response, 200, { jsonrpc: "2.0", id, result: { tools: toolDefinitions } });
          return;
        }
        if (parsed.method === "tools/call") {
          const params = parsed.params as { name?: unknown; arguments?: unknown } | undefined;
          if (params?.name === "workspace_agents") {
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(visibleAgents(await getAgentAdapter())) }] } });
            return;
          }
          if (params?.name === "workspace_zhuji_context") {
            const argumentsValue = params.arguments;
            const context = await (await getRuntime()).zhujiContext(characterIdValue(argumentsValue));
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(context) }] } });
            return;
          }
          if (params?.name === "workspace_zhuji_submit") {
            const result = await (await getRuntime()).submitZhujiProposal(params.arguments, { actor, attachments: [] });
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }] } });
            return;
          }
          if (params?.name === "workspace_template_context") {
            const kind = templateKindValue(params.arguments);
            if (kind === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, error: { code: -32602, message: "kind is required" } });
              return;
            }
            const context = await (await getRuntime()).templateContext(kind as Parameters<WorkspaceRuntime["templateContext"]>[0]);
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(context) }] } });
            return;
          }
          if (params?.name === "workspace_template_submit") {
            const result = await (await getRuntime()).submitTemplateProposal(params.arguments, { actor, attachments: [] });
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }] } });
            return;
          }
          if (params?.name === "workspace_issue_update") {
            const input = issueUpdateValue(params.arguments);
            if (input === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, error: { code: -32602, message: "issue_id, action and reason are required" } });
              return;
            }
            const { agent, ...issue } = input;
            const result = await (await getRuntime()).updateIssue(issue, { actor, attachments: [] }, agent === undefined ? {} : { agent });
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }] } });
            return;
          }
          if (params?.name === "workspace_authoring_context") {
            const context = await (await getRuntime()).authoringKnowledgeContext();
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(context) }] } });
            return;
          }
          if (params?.name === "workspace_source_candidates") {
            const candidates = await (await getRuntime()).sourceCandidates();
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify({ candidates }) }] } });
            return;
          }
          if (params?.name === "workspace_source_select") {
            const decisions = sourceSelectionValue(params.arguments);
            if (decisions === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, error: { code: -32602, message: "decisions are required" } });
              return;
            }
            const result = await (await getRuntime()).selectSourceCandidates(decisions, { actor, attachments: [] });
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }] } });
            return;
          }
          if (params?.name === "workspace_adaptation_decision") {
            const decision = adaptationDecisionValue(params.arguments);
            if (decision === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, error: { code: -32602, message: "topic, choice and rationale are required" } });
              return;
            }
            const result = await (await getRuntime()).createAdaptationDecision(decision, { actor, attachments: [] });
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }] } });
            return;
          }
          if (params?.name === "workspace_status") {
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(options.projectManager === undefined ? await options.runtime!.status() : await options.projectManager.status()) }] } });
            return;
          }
          if (params?.name === "workspace_interview_context") {
            const context = await (await getRuntime()).interviewContext();
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(context) }] } });
            return;
          }
          if (params?.name === "workspace_interview_answer") {
            const answer = answerValue(params.arguments);
            if (answer === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, error: { code: -32602, message: "answer is required" } });
              return;
            }
            const result = options.projectManager === undefined
              ? await (await getRuntime()).answerInterview(answer, { actor, attachments: [] })
              : await options.projectManager.answerInterview(answer, { actor, attachments: [] });
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }] } });
            return;
          }
          if (params?.name === "workspace_projects") {
            if (options.projectManager === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify({ projects: [] }) }] } });
            } else {
              const manager = options.projectManager;
              await manager.ensureRuntime();
              const projects = await manager.listProjects();
              const current = await manager.repository.read();
              const visible = current.project_status === "uninitialized" && current.interview.status === "idle" && current.operations.length === 0
                ? projects.filter((project) => project.project_id !== current.project_id)
                : projects;
              json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify({ projects: visible }) }] } });
            }
            return;
          }
          if (params?.name === "workspace_project_select") {
            const project = projectValue(params.arguments);
            if (project === undefined || options.projectManager === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, error: { code: -32602, message: project === undefined ? "project is required" : "project manager is required" } });
              return;
            }
            const selected = await options.projectManager.select(project);
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(selected) }] } });
            return;
          }
          if (params?.name === "workspace_request") {
            const requestText = requestValue(params.arguments);
            if (requestText === undefined) {
              json(response, 200, { jsonrpc: "2.0", id, error: { code: -32602, message: "request is required" } });
              return;
            }
            const requestedAgent = agentValue(params.arguments);
            const result: RequestResult = options.projectManager === undefined
              ? await (await getAgentAdapter()).request({ request: requestText, context: { actor, attachments: [] }, ...(requestedAgent === undefined ? {} : { agent: requestedAgent }) })
              : await options.projectManager.request(requestText, { actor, attachments: [] }, requestedAgent === undefined ? {} : { agent: requestedAgent });
            json(response, 200, { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }] } });
            return;
          }
          json(response, 200, { jsonrpc: "2.0", id, error: { code: -32601, message: "tool not found" } });
          return;
        }
        json(response, 200, { jsonrpc: "2.0", id, error: { code: -32601, message: "method not found" } });
        return;
      }
      json(response, 404, { error: "NOT_FOUND" });
    } catch (error) {
      const errorCode = error !== null && typeof error === "object" && "code" in error && typeof (error as { code?: unknown }).code === "string" ? (error as { code: string }).code : "";
      const recoverableInput = error !== null && typeof error === "object" && "recoverable" in error && (error as { recoverable?: unknown }).recoverable === true && /^(?:AGENT_|INTERVIEW_|PROJECT_|REQUEST_|ISSUE_|TEMPLATE_|ZHUJI_)/u.test(errorCode);
      const details = error !== null && typeof error === "object" && "details" in error ? (error as { details?: unknown }).details : undefined;
      json(response, recoverableInput ? 400 : 500, { error: error instanceof Error ? error.message : String(error), ...(details === undefined ? {} : { details }) });
    }
  });
  server.once("close", () => worker.stop());
  return Object.assign(server, { workspaceWorker: worker });
}

export async function startWorkspaceServer(options: { port?: number; host?: string; projectRoot?: string; projectId?: string; actor?: string } = {}): Promise<Server> {
  const projectRoot = options.projectRoot ?? process.env.ST_WORKSPACE_PROJECT_ROOT ?? "projects";
  const fetcher = new HttpSourceFetcher();
  // An explicitly supplied root is already a complete workspace selection;
  // do not let an inherited project environment variable silently redirect it.
  // Environment-based project selection remains available for the default root
  // and for callers that pass projectId explicitly.
  const requestedProject = options.projectId ?? (options.projectRoot === undefined ? process.env.ST_WORKSPACE_PROJECT : undefined);
  const selectedProject = typeof requestedProject === "string" && requestedProject.trim().length > 0 ? requestedProject.trim() : undefined;
  const manager = selectedProject === undefined
    ? new WorkspaceProjectManager({ root: projectRoot, createRuntime: (repository) => new WorkspaceRuntime(repository, { fetcher: fetcher.fetch, interviewRequired: true, attachmentStore: new FileAttachmentStore(projectRoot, repository.projectId) }) })
    : undefined;
  if (manager !== undefined) await manager.ensureRuntime();
  const serverOptions: WorkspaceServerOptions = manager !== undefined
    ? { projectManager: manager, actor: options.actor ?? "server" }
    : { runtime: new WorkspaceRuntime(new FileProjectRepository(projectRoot, selectedProject!, { layout: "project", materialize: true }), { fetcher: fetcher.fetch, attachmentStore: new FileAttachmentStore(projectRoot, selectedProject!) }), actor: options.actor ?? "server" };
  const server = createWorkspaceServer(serverOptions);
  await new Promise<void>((resolve) => server.listen(options.port ?? Number(process.env.ST_WORKSPACE_PORT ?? 8787), options.host ?? "127.0.0.1", resolve));
  return server;
}

/* c8 ignore next 3 -- the server entrypoint is exercised through startWorkspaceServer tests. */
if (process.argv[1]?.endsWith("/server/dist/index.js") || process.argv[1]?.endsWith("\\server\\dist\\index.js")) {
  await startWorkspaceServer();
  console.log(`ST Workspace server listening on http://127.0.0.1:${process.env.ST_WORKSPACE_PORT ?? "8787"}`);
}
