import { templateProposalJsonSchema, zhujiProposalJsonSchema } from "@st-workspace/core";

const supportedMcpProtocolVersions = new Set(["2025-11-25", "2025-06-18"]);

export function mcpProtocolVersion(params: unknown): string {
  if (params !== null && typeof params === "object") {
    const requested = (params as { protocolVersion?: unknown }).protocolVersion;
    if (typeof requested === "string" && supportedMcpProtocolVersions.has(requested)) return requested;
  }
  return "2025-11-25";
}

// OpenCode's MCP schema validator requires every tool input schema to declare
// a top-level object type. The template contract is a oneOf of object shapes,
// so the generated JSON Schema omits that redundant discriminator. Adding it
// at the MCP boundary preserves the contract while keeping the schema valid
// for OpenCode and other strict MCP clients.
const templateProposalMcpInputSchema: Record<string, unknown> = { ...(templateProposalJsonSchema as Record<string, unknown>), type: "object" };

// The MCP surface must stay a high-level contract: internal operation and
// storage fields (project ids, revisions, capabilities, stages, steps, file
// paths, encoded payloads) are stripped from the exposed JSON Schema. The
// authoritative validation still runs through the zod contract server-side.
const exposedSchemaKeyPattern = /project_id|revision|capability|stage|steps|file_path|bytes_base64/iu;

function sanitizeJsonSchema(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sanitizeJsonSchema).filter((item) => typeof item !== "string" || !exposedSchemaKeyPattern.test(item));
  if (value !== null && typeof value === "object") {
    const output: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) {
      if (exposedSchemaKeyPattern.test(key)) continue;
      output[key] = sanitizeJsonSchema(item);
    }
    return output;
  }
  return value;
}

const sanitizedTemplateProposalMcpInputSchema = sanitizeJsonSchema(templateProposalMcpInputSchema);

export const toolDefinitions = [
  {
    name: "workspace_request",
    description: "Execute a natural-language workspace intent.",
    inputSchema: { type: "object", additionalProperties: false, properties: { request: { type: "string" }, agent: { type: "string", description: "Optional visible Agent id or alias. Omit to let Director route the intent." } }, required: ["request"] },
  },
  {
    name: "workspace_status",
    description: "Read the current workspace operation status.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_agents",
    description: "List the visible Agents, their roles, and the default Director route.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_zhuji_context",
    description: "Read the Zhuji Creator contract, seven module guides, JSON Schema, and existing module instances.",
    inputSchema: { type: "object", additionalProperties: false, properties: { character_id: { type: "string", description: "Optional character id used to filter existing module instances." } } },
  },
  {
    name: "workspace_zhuji_submit",
    description: "Submit one validated Zhuji module proposal. The proposal must match the seven-module JSON Schema.",
    inputSchema: zhujiProposalJsonSchema,
  },
  {
    name: "workspace_template_context",
    description: "Read the fixed template contract, JSON Schema, guide and existing examples for one Agent/Skill output kind.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        kind: {
          type: "string",
          enum: ["character", "zhuji", "palette", "wardrobe", "greetings", "relationships", "world", "conversion", "import_analysis", "review", "source_research", "fact_curation", "fact_review", "plugin", "director_routing"],
        },
      },
      required: ["kind"],
    },
  },
  {
    name: "workspace_template_submit",
    description: "Submit one validated high-level template value. Internal operation and storage details are generated by the workspace.",
    inputSchema: sanitizedTemplateProposalMcpInputSchema,
  },
  {
    name: "workspace_issue_update",
    description: "Resolve, ignore, or override one review issue. Ignore and override are allowed only for overridable findings and every action needs a reason.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        issue_id: { type: "string" },
        action: { type: "string", enum: ["resolve", "ignore", "override"] },
        reason: { type: "string" },
        severity: { type: "string", enum: ["critical", "error", "warning", "info"] },
        agent: { type: "string", description: "Optional trusted execution agent; defaults to Director." },
      },
      required: ["issue_id", "action", "reason"],
    },
  },
  {
    name: "workspace_authoring_context",
    description: "Read Blueprint, accepted and unresolved Facts, source records, and adaptation decisions for Creator authoring.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_source_candidates",
    description: "List source candidates and their explicit selection state.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_source_select",
    description: "Explicitly approve or reject source candidate ids before source ingestion.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        decisions: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: { candidate_id: { type: "string" }, decision: { type: "string", enum: ["approve", "reject"] } },
            required: ["candidate_id", "decision"],
          },
        },
      },
      required: ["decisions"],
    },
  },
  {
    name: "workspace_adaptation_decision",
    description: "Record how a deliberate Blueprint-versus-canon difference should be handled.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        topic: { type: "string" },
        choice: { type: "string", enum: ["keep_blueprint", "adopt_fact", "blend", "defer"] },
        blueprint_refs: { type: "array", items: { type: "string" } },
        fact_refs: { type: "array", items: { type: "string" } },
        rationale: { type: "string" },
      },
      required: ["topic", "choice", "rationale"],
    },
  },
  {
    name: "workspace_interview_context",
    description: "Read exactly one current high-level project interview question and its saved answers. Do not treat this as a batch questionnaire.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_interview_answer",
    description: "Answer exactly the current project interview question. The workspace stores one answer atomically and returns one next question; it does not accept batch answers.",
    inputSchema: { type: "object", additionalProperties: false, properties: { answer: { type: "string" } }, required: ["answer"] },
  },
  {
    name: "workspace_projects",
    description: "List projects available inside the workspace projects folder.",
    inputSchema: { type: "object", additionalProperties: false, properties: {} },
  },
  {
    name: "workspace_project_select",
    description: "Select an existing project by its visible name or folder name.",
    inputSchema: { type: "object", additionalProperties: false, properties: { project: { type: "string" } }, required: ["project"] },
  },
] as const;
