import {
  pluginContributionsSchema,
  type HtmlSource,
  type JsonValue,
  type PluginContributions,
  type Revision,
} from "@card-workspace/schemas";

import { revisionFor, safeJsString } from "../../canonical.js";
import { generateScopedCss } from "./css-scope.js";
import { renderHtmlComponent, type RenderedHtmlComponent } from "./generate-markup.js";
import { generateHtmlRegexScripts } from "./generate-regex.js";
import { generateHtmlRuntimeScript } from "./generate-runtime.js";
import { htmlPolicyVersion } from "./policy-v1.js";
import { validateHtmlSource, type HtmlValidationContext } from "./validate.js";

function pathRegistryJson(context: HtmlValidationContext): JsonValue | undefined {
  const registry = context.mvuPathRegistry;
  if (!registry) return undefined;
  return {
    schema_version: registry.schema_version,
    paths: Object.fromEntries(Object.entries(registry.paths).map(([path, binding]) => [path, {
      id: binding.id,
      label: binding.label,
      kind: binding.kind,
      path: binding.path,
      read_path: binding.read_path,
      patch_path: binding.patch_path,
      default: binding.default,
      ...(binding.min === undefined ? {} : { min: binding.min }),
      ...(binding.max === undefined ? {} : { max: binding.max }),
      ...(binding.values === undefined ? {} : { values: [...binding.values] }),
      writable: binding.writable,
      visibility: binding.visibility,
      container: binding.container,
    }])),
    by_id: { ...registry.by_id },
    runtime_read_paths: { ...registry.runtime_read_paths },
    json_patch_paths: { ...registry.json_patch_paths },
  };
}

export interface HtmlCompilation {
  readonly source: HtmlSource;
  readonly rendered: readonly RenderedHtmlComponent[];
  readonly css: string;
  readonly artifact_revision: Revision;
  readonly contributions: PluginContributions;
}

export function compileHtmlSource(
  source: HtmlSource,
  context: { readonly mvuPathRegistry?: HtmlValidationContext["mvuPathRegistry"]; readonly greetingIds?: readonly string[] } = {},
): HtmlCompilation {
  const validated = validateHtmlSource(source, {
    ...(context.mvuPathRegistry === undefined ? {} : { mvuPathRegistry: context.mvuPathRegistry }),
    ...(context.greetingIds === undefined ? {} : { greetingIds: context.greetingIds }),
  });
  const rendered = validated.source.components.map(renderHtmlComponent);
  const css = generateScopedCss(rendered.map((component) => component.id));
  const runtimeBindings = validated.source.components.flatMap((component) => {
    const bindings = validated.bindingsByComponent.get(component.id) ?? [];
    return component.binding_paths.map((path, index) => ({
      component_id: component.id,
      path,
      writable: bindings[index]?.writable ?? false,
    }));
  });
  const runtime = generateHtmlRuntimeScript(css, runtimeBindings);
  const pathRegistry = pathRegistryJson(validated);
  const greetingIds = validated.source.features.includes("greeting_selector")
    ? validated.greetingIds ?? []
    : [];
  const resolvedSourceHash = revisionFor(validated.source);
  const artifactRevision = revisionFor({
    canonical_source_revision: resolvedSourceHash,
    policy: htmlPolicyVersion,
    path_registry: pathRegistry ?? null,
    greeting_ids: greetingIds,
    rendered: rendered.map((component) => ({
      id: component.id,
      feature: component.feature,
      markup: component.markup,
      css: component.css,
    })),
  });
  const greetingComponents = rendered.filter((component) => component.feature === "greeting_selector");
  const greetingOperations = greetingIds.flatMap((greetingId) => greetingComponents.map((component) => ({
    greeting_id: greetingId,
    mode: "append" as const,
    content: component.markup,
  })));
  const metadata: Record<string, JsonValue> = {
    source_schema_version: validated.source.schema_version,
    project_kind: validated.source.project_kind,
    resolved_source_hash: resolvedSourceHash,
    policy: htmlPolicyVersion,
    features: [...validated.source.features],
    component_ids: rendered.map((component) => component.id),
    css,
    runtime_bindings: runtimeBindings,
    runtime_policy: safeJsString(htmlPolicyVersion),
    ...(pathRegistry === undefined ? {} : { path_registry: pathRegistry }),
  };
  const contributions = pluginContributionsSchema.parse({
    schema_version: 1,
    plugin_id: "official.html",
    implementation: validated.source.implementation,
    artifact_revision: artifactRevision,
    lore_entries: [],
    regex_scripts: generateHtmlRegexScripts(validated.source, rendered),
    helper_scripts: [{
      type: "script",
      enabled: true,
      id: "official.html.runtime",
      name: "Card Workspace HTML runtime",
      content: runtime,
      info: "Generated by html-policy@1; no authored markup, CSS, or script is accepted.",
       button: { enabled: false, buttons: [] },
      data: {},
    }],
    greeting_operations: greetingOperations,
    metadata,
  });
  return {
    source: validated.source,
    rendered,
    css,
    artifact_revision: artifactRevision,
    contributions,
  };
}

export { validateHtmlSource } from "./validate.js";
export type { HtmlValidationContext } from "./validate.js";
